parameters:
#    acme_admin.example.class: Acme\AdminBundle\Example

services:
#    acme_admin.example:
#        class: %acme_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
