security:
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            http_basic:
                realm: "Secured Demo Area"

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }

    providers:
         main:
            entity: { class: Acme\UserBundle\Entity\User, property: username }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext